import 'package:flutter/material.dart';
import 'package:flutterapp/relishersapp/generated31cardlistwidget/generated/GeneratedBarsTopbars1Widget17.dart';
import 'package:flutterapp/relishersapp/generated31cardlistwidget/generated/GeneratedPaymentmethodsWidget.dart';

/* Frame 31-Card list
    Autogenerated by FlutLab FTF Generator
  */
class Generated31CardlistWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 88.0,
                child: GeneratedBarsTopbars1Widget17(),
              ),
              Positioned(
                left: 20.0,
                top: 112.0,
                right: null,
                bottom: null,
                width: 355.0,
                height: 216.0,
                child: GeneratedPaymentmethodsWidget(),
              )
            ]),
      ),
    ));
  }
}
