import 'package:flutter/material.dart';
import 'package:flutterapp/relishersapp/generatedicons3434widget/generated/GeneratedIcons3434Widget1.dart';
import 'package:flutterapp/relishersapp/generatedicons3434widget/generated/GeneratedIcon34Widget.dart';

/* Frame Icons(34*34)
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIcons3434Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 523.0,
        height: 528.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 60.0,
                top: 124.0,
                right: null,
                bottom: null,
                width: 404.0,
                height: 330.0,
                child: GeneratedIcon34Widget(),
              ),
              Positioned(
                left: 60.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 212.0,
                height: 26.0,
                child: GeneratedIcons3434Widget1(),
              )
            ]),
      ),
    ));
  }
}
