import 'package:flutter/material.dart';
import 'package:flutterapp/relishersapp/generated01walkthroughwidget/generated/GeneratedIllustrationsWidget.dart';
import 'package:flutterapp/relishersapp/generated01walkthroughwidget/generated/GeneratedTextWidget.dart';
import 'package:flutterapp/relishersapp/generated01walkthroughwidget/generated/GeneratedCTAPrimaryWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/relishersapp/generated01walkthroughwidget/generated/GeneratedIndicatorWidget.dart';
import 'package:flutterapp/relishersapp/generated01walkthroughwidget/generated/GeneratedWelcometoRelishersWidget.dart';
import 'package:flutterapp/relishersapp/generated01walkthroughwidget/generated/GeneratedG12Widget.dart';
import 'package:flutterapp/relishersapp/generated01walkthroughwidget/generated/GeneratedIPhoneXStatusBarsStatusBarWidget.dart';

/* Frame 01-Walkthrough
    Autogenerated by FlutLab FTF Generator
  */
class Generated01WalkthroughWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedIPhoneXStatusBarsStatusBarWidget(),
              ),
              Positioned(
                left: 48.0,
                top: 537.0,
                right: null,
                bottom: null,
                width: 277.0,
                height: 78.0,
                child: GeneratedTextWidget(),
              ),
              Positioned(
                left: 164.0,
                top: 647.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 5.0,
                child: GeneratedIndicatorWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 1.00431787109375;

                  final double height =
                      constraints.maxHeight * 0.4724087268848137;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: constraints.maxHeight * 0.14655172413793102,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedIllustrationsWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.17333333333333334;

                  final double height =
                      constraints.maxHeight * 0.08004926108374384;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.104,
                        y: constraints.maxHeight * 0.18842364532019704,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedG12Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.6933333333333334;

                  final double height =
                      constraints.maxHeight * 0.06280788177339902;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.2826666666666667,
                        y: constraints.maxHeight * 0.1022167487684729,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedWelcometoRelishersWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 18.0,
                top: 684.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 48.0,
                child: GeneratedCTAPrimaryWidget(),
              )
            ]),
      ),
    ));
  }
}
