import 'package:flutter/material.dart';
import 'package:flutterapp/relishersapp/generated0welcomewidget/generated/GeneratedIllustrationWidget3.dart';
import 'package:flutterapp/relishersapp/generated0welcomewidget/generated/GeneratedComponent1Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/relishersapp/generated0welcomewidget/generated/GeneratedCTAPrimaryWidget17.dart';
import 'package:flutterapp/relishersapp/generated0welcomewidget/generated/GeneratedCircleBackgroundWidget.dart';
import 'package:flutterapp/relishersapp/generated0welcomewidget/generated/GeneratedTextWidget23.dart';
import 'package:flutterapp/relishersapp/generated0welcomewidget/generated/GeneratedWelcometoRelishersWidget3.dart';
import 'package:flutter_statusbarcolor/flutter_statusbarcolor.dart';
/* Frame 0- Welcome
    Autogenerated by FlutLab FTF Generator
  */
class Generated0WelcomeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    FlutterStatusbarcolor.setNavigationBarColor(Colors.transparent);
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -101.0,
                top: -49.0,
                right: null,
                bottom: null,
                width: 437.0,
                height: 437.0,
                child: GeneratedCircleBackgroundWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 496.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 128.0,
                child: GeneratedTextWidget23(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.5693099772135417;

                  final double height =
                      constraints.maxHeight * 0.2993775541559229;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.21333333333333335,
                        y: constraints.maxHeight * 0.26108374384236455,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedIllustrationWidget3(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: -113.0,
                top: 130.0,
                right: null,
                bottom: null,
                width: 486.0,
                height: 68.0,
                child: GeneratedComponent1Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.6933333333333334;

                  final double height =
                      constraints.maxHeight * 0.06280788177339902;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.24533333333333332,
                        y: constraints.maxHeight * 0.11699507389162561,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedWelcometoRelishersWidget3(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 15.0,
                top: 650.0,
                right: null,
                bottom: null,
                width: 330.0,
                height: 48.0,
                child: ElevatedButton(
                  style: ButtonStyle(
                    shape: MaterialStateProperty.all<RoundedRectangleBorder>(
                        RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(7.0),
                        ))
                    ,backgroundColor: MaterialStateProperty.all(Color.fromARGB(255, 238, 166, 52)),
                    padding: MaterialStateProperty.all(EdgeInsets.all(13)),
                  ),

                  onPressed: () {  },
                  child: Text("Get Started",style: TextStyle(
                      fontSize: 15.0,fontFamily: 'Yu Gothic UI',
                    fontWeight: FontWeight.w700)),
                ),
              )
            ]),
      ),
    ));
  }
}
