import 'package:flutter/material.dart';
import 'package:flutterapp/relishersapp/generated34refertofriendwidget/generated/GeneratedRefertofriendWidget.dart';
import 'package:flutterapp/relishersapp/generated34refertofriendwidget/generated/GeneratedBarsTopbars1Widget15.dart';
import 'package:flutterapp/relishersapp/generated34refertofriendwidget/generated/GeneratedIconCreditcardWidget1.dart';

/* Frame 34-Refer To Friend
    Autogenerated by FlutLab FTF Generator
  */
class Generated34ReferToFriendWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 88.0,
                child: GeneratedBarsTopbars1Widget15(),
              ),
              Positioned(
                left: 128.0,
                top: 135.0,
                right: null,
                bottom: null,
                width: 125.0,
                height: 122.3731689453125,
                child: GeneratedIconCreditcardWidget1(),
              ),
              Positioned(
                left: 35.0,
                top: 289.0,
                right: null,
                bottom: null,
                width: 312.0,
                height: 161.0,
                child: GeneratedRefertofriendWidget(),
              )
            ]),
      ),
    ));
  }
}
