import 'package:flutter/material.dart';
import 'package:flutterapp/relishersapp/generated19filterswidget/generated/GeneratedCategoriesWidget.dart';
import 'package:flutterapp/relishersapp/generated19filterswidget/generated/GeneratedDietaryWidget.dart';
import 'package:flutterapp/relishersapp/generated19filterswidget/generated/GeneratedBarsTopbars1Widget8.dart';
import 'package:flutterapp/relishersapp/generated19filterswidget/generated/GeneratedCTAPrimaryWidget11.dart';
import 'package:flutterapp/relishersapp/generated19filterswidget/generated/GeneratedPriceRangeWidget.dart';

/* Frame 19-Filters
    Autogenerated by FlutLab FTF Generator
  */
class Generated19FiltersWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 112.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 180.0,
                child: GeneratedCategoriesWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 326.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 130.0,
                child: GeneratedDietaryWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 490.0,
                right: null,
                bottom: null,
                width: 384.0,
                height: 106.0,
                child: GeneratedPricerangeWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 734.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 48.0,
                child: GeneratedCTAPrimaryWidget11(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 88.0,
                child: GeneratedBarsTopbars1Widget8(),
              )
            ]),
      ),
    ));
  }
}
