import 'package:flutter/material.dart';
import 'package:flutterapp/relishersapp/generated37browsefoodswidget/generated/GeneratedBarsTopbars1Widget20.dart';
import 'package:flutterapp/relishersapp/generated37browsefoodswidget/generated/GeneratedBrowsefoodsWidget.dart';

/* Frame 37-Browse foods
    Autogenerated by FlutLab FTF Generator
  */
class Generated37BrowsefoodsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1363.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 375.0,
                      height: 1227.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 88.0,
                              child: GeneratedBarsTopbars1Widget20(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 112.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 1251.0,
                              child: GeneratedBrowsefoodsWidget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
