import 'package:flutter/material.dart';
import 'package:flutterapp/relishersapp/generated10confirmphonenumberwidget/generated/GeneratedCTAPrimaryWidget8.dart';
import 'package:flutterapp/relishersapp/generated10confirmphonenumberwidget/generated/GeneratedTextWidget8.dart';
import 'package:flutterapp/relishersapp/generated10confirmphonenumberwidget/generated/GeneratedKeyboards2Widget1.dart';
import 'package:flutterapp/relishersapp/generated10confirmphonenumberwidget/generated/GeneratedBySigningupyouagreetoourTermsConditionsPrivacyPolicyWid1.dart';
import 'package:flutterapp/relishersapp/generated10confirmphonenumberwidget/generated/GeneratedEntercodeWidget.dart';
import 'package:flutterapp/relishersapp/generated10confirmphonenumberwidget/generated/GeneratedResendagainWidget.dart';
import 'package:flutterapp/relishersapp/generated10confirmphonenumberwidget/generated/GeneratedBarsTopbars1Widget5.dart';

/* Frame 10-Confirm phone number
    Autogenerated by FlutLab FTF Generator
  */
class Generated10ConfirmphonenumberWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 88.0,
                child: GeneratedBarsTopbars1Widget5(),
              ),
              Positioned(
                left: 38.0,
                top: 112.0,
                right: null,
                bottom: null,
                width: 299.0,
                height: 80.0,
                child: GeneratedTextWidget8(),
              ),
              Positioned(
                left: 42.0,
                top: 238.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 40.0,
                child: GeneratedEntercodeWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 317.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 48.0,
                child: GeneratedCTAPrimaryWidget8(),
              ),
              Positioned(
                left: 88.0,
                top: 389.0,
                right: null,
                bottom: null,
                width: 198.0,
                height: 9.0,
                child: GeneratedResendagainWidget(),
              ),
              Positioned(
                left: 45.0,
                top: 432.0,
                right: null,
                bottom: null,
                width: 286.0,
                height: 38.0,
                child:
                    GeneratedBySigningupyouagreetoourTermsConditionsPrivacyPolicyWid1(),
              ),
              Positioned(
                left: 0.0,
                top: 521.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 291.0,
                child: GeneratedKeyboards2Widget1(),
              )
            ]),
      ),
    ));
  }
}
