import 'package:flutter/material.dart';
import 'package:flutterapp/relishersapp/generated17yourorderswidget/generated/GeneratedCTAPrimaryWidget10.dart';
import 'package:flutterapp/relishersapp/generated17yourorderswidget/generated/GeneratedOrderlistWidget2.dart';
import 'package:flutterapp/relishersapp/generated17yourorderswidget/generated/GeneratedTotalWidget.dart';
import 'package:flutterapp/relishersapp/generated17yourorderswidget/generated/GeneratedAddmoreWidget.dart';
import 'package:flutterapp/relishersapp/generated17yourorderswidget/generated/GeneratedBarsTopbars1Widget7.dart';

/* Frame 17-Your Orders
    Autogenerated by FlutLab FTF Generator
  */
class Generated17YourOrdersWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 465.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 96.0,
                child: GeneratedTotalWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 589.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 98.0,
                child: GeneratedAddmoreWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 734.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 48.0,
                child: GeneratedCTAPrimaryWidget10(),
              ),
              Positioned(
                left: 20.0,
                top: 112.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 337.0,
                child: GeneratedOrderlistWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 88.0,
                child: GeneratedBarsTopbars1Widget7(),
              )
            ]),
      ),
    ));
  }
}
