import 'package:flutter/material.dart';
import 'package:flutterapp/relishersapp/generated28profilesettingswidget/generated/GeneratedProfilesettingsWidget.dart';
import 'package:flutterapp/relishersapp/generated28profilesettingswidget/generated/GeneratedCTAPrimaryWidget14.dart';
import 'package:flutterapp/relishersapp/generated28profilesettingswidget/generated/GeneratedBarsTopbars1Widget12.dart';

/* Frame 28-Profile settings
    Autogenerated by FlutLab FTF Generator
  */
class Generated28ProfilesettingsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 88.0,
                child: GeneratedBarsTopbars1Widget12(),
              ),
              Positioned(
                left: 20.0,
                top: 112.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 316.0,
                child: GeneratedProfilesettingsWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 734.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 48.0,
                child: GeneratedCTAPrimaryWidget14(),
              )
            ]),
      ),
    ));
  }
}
