import 'package:flutter/material.dart';
import 'package:flutterapp/relishersapp/generated07resetemailwidget/generated/GeneratedTextWidget5.dart';
import 'package:flutterapp/relishersapp/generated07resetemailwidget/generated/GeneratedCTAPrimaryWidget5.dart';
import 'package:flutterapp/relishersapp/generated07resetemailwidget/generated/GeneratedBarsTopbars1Widget2.dart';

/* Frame 07-Reset email
    Autogenerated by FlutLab FTF Generator
  */
class Generated07ResetemailWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/Generated05SignInWidget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 375.0,
          height: 812.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 375.0,
                  height: 88.0,
                  child: GeneratedBarsTopbars1Widget2(),
                ),
                Positioned(
                  left: 20.0,
                  top: 112.0,
                  right: null,
                  bottom: null,
                  width: 319.0,
                  height: 81.0,
                  child: GeneratedTextWidget5(),
                ),
                Positioned(
                  left: 20.0,
                  top: 226.0,
                  right: null,
                  bottom: null,
                  width: 335.0,
                  height: 48.0,
                  child: GeneratedCTAPrimaryWidget5(),
                )
              ]),
        ),
      ),
    ));
  }
}
