import 'package:flutter/material.dart';
import 'package:flutterapp/relishersapp/generated33addsocialaccountswidget/generated/GeneratedBarsTopbars1Widget19.dart';
import 'package:flutterapp/relishersapp/generated33addsocialaccountswidget/generated/GeneratedTextWidget21.dart';
import 'package:flutterapp/relishersapp/generated33addsocialaccountswidget/generated/GeneratedSocialsaccountsWidget.dart';

/* Frame 33-Add social accounts
    Autogenerated by FlutLab FTF Generator
  */
class Generated33AddsocialaccountsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 88.0,
                child: GeneratedBarsTopbars1Widget19(),
              ),
              Positioned(
                left: 32.0,
                top: 168.0,
                right: null,
                bottom: null,
                width: 312.0,
                height: 77.0,
                child: GeneratedTextWidget21(),
              ),
              Positioned(
                left: 20.0,
                top: 279.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 106.0,
                child: GeneratedSocialsaccountsWidget(),
              )
            ]),
      ),
    ));
  }
}
