import 'package:flutter/material.dart';
import 'package:flutterapp/relishersapp/generated39singlerestaurantswidget/generated/GeneratedRectangleWidget187.dart';
import 'package:flutterapp/relishersapp/generated39singlerestaurantswidget/generated/GeneratedSingleContentWidget.dart';
import 'package:flutterapp/relishersapp/generated39singlerestaurantswidget/generated/GeneratedTopbarWidget8.dart';

/* Frame 39-Single restaurants
    Autogenerated by FlutLab FTF Generator
  */
class Generated39SinglerestaurantsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -2.0,
                top: 122.0,
                right: null,
                bottom: null,
                width: 377.0,
                height: 690.0,
                child: GeneratedSingleContentWidget(),
              ),
              Positioned(
                left: -6.0,
                top: -262.0,
                right: null,
                bottom: null,
                width: 388.0,
                height: 493.0,
                child: GeneratedRectangleWidget187(),
              ),
              Positioned(
                left: -7.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 88.0,
                child: GeneratedTopbarWidget8(),
              )
            ]),
      ),
    ));
  }
}
