import 'package:flutter/material.dart';
import 'package:flutterapp/relishersapp/generated12typelocationwidget/generated/GeneratedTextWidget10.dart';
import 'package:flutterapp/relishersapp/generated12typelocationwidget/generated/GeneratedTopbarWidget1.dart';
import 'package:flutterapp/relishersapp/generated12typelocationwidget/generated/GeneratedAddressesWidget.dart';
import 'package:flutterapp/relishersapp/generated12typelocationwidget/generated/GeneratedForm4searchactiveWidget.dart';
import 'package:flutterapp/relishersapp/generated12typelocationwidget/generated/GeneratedKeyboards1Widget1.dart';

/* Frame 12-Type location
    Autogenerated by FlutLab FTF Generator
  */
class Generated12TypelocationWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 29.0,
                top: 112.0,
                right: null,
                bottom: null,
                width: 318.0,
                height: 80.0,
                child: GeneratedTextWidget10(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 88.0,
                child: GeneratedTopbarWidget1(),
              ),
              Positioned(
                left: 20.0,
                top: 226.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 48.0,
                child: GeneratedForm4searchactiveWidget(),
              ),
              Positioned(
                left: 36.0,
                top: 290.0,
                right: null,
                bottom: null,
                width: 339.0,
                height: 330.0,
                child: GeneratedAddressesWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 479.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 333.0,
                child: GeneratedKeyboards1Widget1(),
              )
            ]),
      ),
    ));
  }
}
