import 'package:flutter/material.dart';
import 'package:flutterapp/relishersapp/generatedbannerwidget1/generated/Generated15Widget1.dart';
import 'package:flutterapp/relishersapp/generatedbannerwidget1/generated/Generated101Widget1.dart';
import 'package:flutterapp/relishersapp/generatedbannerwidget1/generated/GeneratedPathWidget255.dart';
import 'package:flutterapp/relishersapp/generatedbannerwidget1/generated/GeneratedBgWidget257.dart';
import 'package:flutterapp/relishersapp/generatedbannerwidget1/generated/GeneratedBgWidget256.dart';
import 'package:flutterapp/relishersapp/generatedbannerwidget1/generated/GeneratedPathWidget257.dart';
import 'package:flutterapp/relishersapp/generatedbannerwidget1/generated/GeneratedPathWidget256.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/relishersapp/generatedbannerwidget1/generated/GeneratedOvalWidget149.dart';
import 'package:flutterapp/relishersapp/generatedbannerwidget1/generated/GeneratedOvalWidget148.dart';

/* Component Banner
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBannerWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 335.0,
      height: 170.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth;

                final double height = constraints.maxHeight;

                return Stack(children: [
                  TransformHelper.translate(
                      x: 0,
                      y: 0,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedBgWidget256(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 335.0,
              height: 170.0,
              child: GeneratedBgWidget257(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.14328358208955225;

                final double height =
                    constraints.maxHeight * 0.2823529411764706;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.878379252419543,
                      y: constraints.maxHeight * 0.5338932261747472,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: Generated15Widget1(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                double percentWidth = 0.01671641762576886;
                double scaleX =
                    (constraints.maxWidth * percentWidth) / 5.599999904632568;

                double percentHeight = 0.009411764846128576;
                double scaleY =
                    (constraints.maxHeight * percentHeight) / 1.600000023841858;

                return Stack(children: [
                  TransformHelper.translateAndScale(
                      translateX: constraints.maxWidth * 0.7940298507462686,
                      translateY: constraints.maxHeight * 0.6257676966050092,
                      translateZ: 0,
                      scaleX: scaleX,
                      scaleY: scaleY,
                      scaleZ: 1,
                      child: GeneratedPathWidget255())
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                double percentWidth = 0.009958393182327498;
                double scaleX =
                    (constraints.maxWidth * percentWidth) / 3.336061716079712;

                double percentHeight = 0.029885331322165098;
                double scaleY =
                    (constraints.maxHeight * percentHeight) / 5.080506324768066;

                return Stack(children: [
                  TransformHelper.translateAndScale(
                      translateX: constraints.maxWidth * 0.8236402824743471,
                      translateY: constraints.maxHeight * 0.5352941176470588,
                      translateZ: 0,
                      scaleX: scaleX,
                      scaleY: scaleY,
                      scaleZ: 1,
                      child: GeneratedPathWidget256())
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                double percentWidth = 0.010447761194029851;
                double scaleX = (constraints.maxWidth * percentWidth) / 3.5;

                double percentHeight = 0.0292115099289838;
                double scaleY =
                    (constraints.maxHeight * percentHeight) / 4.965956687927246;

                return Stack(children: [
                  TransformHelper.translateAndScale(
                      translateX: constraints.maxWidth * 0.8080597379314366,
                      translateY: constraints.maxHeight * 0.6910618052763098,
                      translateZ: 0,
                      scaleX: scaleX,
                      scaleY: scaleY,
                      scaleZ: 1,
                      child: GeneratedPathWidget257())
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                double percentWidth = 0.007761193745171846;
                double scaleX =
                    (constraints.maxWidth * percentWidth) / 2.5999999046325684;

                double percentHeight = 0.015294117086073932;
                double scaleY = (constraints.maxHeight * percentHeight) /
                    2.5999999046325684;

                return Stack(children: [
                  TransformHelper.translateAndScale(
                      translateX: constraints.maxWidth * 0.7943283764284048,
                      translateY: constraints.maxHeight * 0.6798853257123162,
                      translateZ: 0,
                      scaleX: scaleX,
                      scaleY: scaleY,
                      scaleZ: 1,
                      child: GeneratedOvalWidget148())
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                double percentWidth = 0.007761193745171846;
                double scaleX =
                    (constraints.maxWidth * percentWidth) / 2.5999999046325684;

                double percentHeight = 0.015294117086073932;
                double scaleY = (constraints.maxHeight * percentHeight) /
                    2.5999999046325684;

                return Stack(children: [
                  TransformHelper.translateAndScale(
                      translateX: constraints.maxWidth * 0.8002985256821362,
                      translateY: constraints.maxHeight * 0.5687088461483226,
                      translateZ: 0,
                      scaleX: scaleX,
                      scaleY: scaleY,
                      scaleZ: 1,
                      child: GeneratedOvalWidget149())
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.11404203728063783;

                final double height =
                    constraints.maxHeight * 0.22472989699419807;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.9402087766732743,
                      y: constraints.maxHeight * 0.7660155352424173,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: Generated101Widget1(),
                      ))
                ]);
              }),
            )
          ]),
    ));
  }
}
