import 'package:flutter/material.dart';
import 'package:flutterapp/relishersapp/generated06forgotpasswordwidget/generated/GeneratedKeyboards1Widget.dart';
import 'package:flutterapp/relishersapp/generated06forgotpasswordwidget/generated/GeneratedCTAPrimaryWidget4.dart';
import 'package:flutterapp/relishersapp/generated06forgotpasswordwidget/generated/GeneratedBarsTopbars1Widget1.dart';
import 'package:flutterapp/relishersapp/generated06forgotpasswordwidget/generated/GeneratedTextWidget4.dart';
import 'package:flutterapp/relishersapp/generated06forgotpasswordwidget/generated/GeneratedForm2ActiveWidget.dart';

/* Frame 06-Forgot password
    Autogenerated by FlutLab FTF Generator
  */
class Generated06ForgotpasswordWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 88.0,
                child: GeneratedBarsTopbars1Widget1(),
              ),
              Positioned(
                left: 20.0,
                top: 112.0,
                right: null,
                bottom: null,
                width: 274.0,
                height: 80.0,
                child: GeneratedTextWidget4(),
              ),
              Positioned(
                left: 20.0,
                top: 226.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 65.0,
                child: GeneratedForm2ActiveWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 315.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 48.0,
                child: GeneratedCTAPrimaryWidget4(),
              ),
              Positioned(
                left: 0.0,
                top: 479.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 333.0,
                child: GeneratedKeyboards1Widget(),
              )
            ]),
      ),
    ));
  }
}
