import 'package:flutter/material.dart';
import 'package:flutterapp/relishersapp/generated26ordercompletewidget/generated/GeneratedOrderlistWidget8.dart';
import 'package:flutterapp/relishersapp/generated26ordercompletewidget/generated/GeneratedTotalWidget2.dart';
import 'package:flutterapp/relishersapp/generated26ordercompletewidget/generated/GeneratedOrderSuccessfullWidget.dart';
import 'package:flutterapp/relishersapp/generated26ordercompletewidget/generated/GeneratedAddmoreWidget4.dart';
import 'package:flutterapp/relishersapp/generated26ordercompletewidget/generated/GeneratedBarsTopbars1Widget11.dart';
import 'package:flutterapp/relishersapp/generated26ordercompletewidget/generated/GeneratedCTAPrimaryWidget13.dart';

/* Frame 26- Order Complete
    Autogenerated by FlutLab FTF Generator
  */
class Generated26OrderCompleteWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          border: Border.all(
            width: 1.0,
            color: Color.fromARGB(255, 0, 0, 0),
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 465.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 100.0,
                child: GeneratedTotalWidget2(),
              ),
              Positioned(
                left: 20.0,
                top: 589.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 98.0,
                child: GeneratedAddmoreWidget4(),
              ),
              Positioned(
                left: 20.0,
                top: 734.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 48.0,
                child: GeneratedCTAPrimaryWidget13(),
              ),
              Positioned(
                left: 20.0,
                top: 112.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 337.0,
                child: GeneratedOrderlistWidget8(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 88.0,
                child: GeneratedBarsTopbars1Widget11(),
              ),
              Positioned(
                left: 12.0,
                top: 434.0,
                right: null,
                bottom: null,
                width: 351.0,
                height: 358.0,
                child: GeneratedOrderSuccessfullWidget(),
              )
            ]),
      ),
    ));
  }
}
