import 'package:flutter/material.dart';
import 'package:flutterapp/relishersapp/generatedstyleguidewidget/generated/GeneratedTypographyWidget.dart';
import 'package:flutterapp/relishersapp/generatedstyleguidewidget/generated/GeneratedColorsWidget.dart';

/* Frame Style Guide
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedStyleGuideWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1187.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1230.0,
                      height: 1187.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 57.0,
                              top: 60.0,
                              right: null,
                              bottom: null,
                              width: 1100.0,
                              height: 244.0,
                              child: GeneratedColorsWidget(),
                            ),
                            Positioned(
                              left: 57.0,
                              top: 404.0,
                              right: null,
                              bottom: null,
                              width: 399.0,
                              height: 682.0,
                              child: GeneratedTypographyWidget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
