import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/relishersapp/generatedctaseconderywidget16/generated/GeneratedRectangleWidget237.dart';
import 'package:flutterapp/relishersapp/generatedctaseconderywidget16/generated/GeneratedTakeawayWidget10.dart';

/* Component CTA/Secondery
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCTASeconderyWidget16 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 113.0,
      height: 38.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 1.0070796461231941;

                final double height = constraints.maxHeight * 1.021052631892656;

                return Stack(children: [
                  TransformHelper.translate(
                      x: 0,
                      y: 0,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedRectangleWidget237(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.7079646017699115;

                final double height =
                    constraints.maxHeight * 0.2894736842105263;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.1592920353982301,
                      y: constraints.maxHeight * 0.3815789473684211,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedTakeawayWidget10(),
                      ))
                ]);
              }),
            )
          ]),
    ));
  }
}
