import 'package:flutter/material.dart';
import 'package:flutterapp/relishersapp/generated36scancardwidget/generated/GeneratedTextWidget22.dart';
import 'package:flutterapp/relishersapp/generated36scancardwidget/generated/GeneratedImageWidget1.dart';
import 'package:flutterapp/relishersapp/generated36scancardwidget/generated/GeneratedOverlayWidget.dart';
import 'package:flutterapp/relishersapp/generated36scancardwidget/generated/GeneratedTopbarWidget6.dart';
import 'package:flutterapp/relishersapp/generated36scancardwidget/generated/GeneratedScaannerWidget.dart';

/* Frame 36-Scan card
    Autogenerated by FlutLab FTF Generator
  */
class Generated36ScancardWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/Generated24YourordersWidget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 375.0,
          height: 812.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 375.0,
                  height: 812.0,
                  child: GeneratedImageWidget1(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 375.0,
                  height: 812.0,
                  child: GeneratedOverlayWidget(),
                ),
                Positioned(
                  left: 76.0,
                  top: 338.0,
                  right: null,
                  bottom: null,
                  width: 224.0,
                  height: 134.0,
                  child: GeneratedScaannerWidget(),
                ),
                Positioned(
                  left: 32.0,
                  top: 201.0,
                  right: null,
                  bottom: null,
                  width: 312.0,
                  height: 77.0,
                  child: GeneratedTextWidget22(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 375.0,
                  height: 88.0,
                  child: GeneratedTopbarWidget6(),
                )
              ]),
        ),
      ),
    ));
  }
}
