import 'package:flutter/material.dart';
import 'package:flutterapp/relishersapp/generated05signinwidget/generated/GeneratedTextWidget3.dart';
import 'package:flutterapp/relishersapp/generated05signinwidget/generated/GeneratedSocialaccountsWidget.dart';
import 'package:flutterapp/relishersapp/generated05signinwidget/generated/GeneratedCreateaccountWidget.dart';
import 'package:flutterapp/relishersapp/generated05signinwidget/generated/GeneratedSigninWidget.dart';
import 'package:flutterapp/relishersapp/generated05signinwidget/generated/GeneratedBarsTopbars1Widget.dart';


/* Frame 05-Sign In
    Autogenerated by FlutLab FTF Generator
  */
class Generated05SignInWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 88.0,
                child: GeneratedBarsTopbars1Widget(),
              ),
              Positioned(
                left: 21.0,
                top: 118.0,
                right: null,
                bottom: null,
                width: 338.0,
                height: 102.0,
                child: GeneratedTextWidget3(),
              ),
              Positioned(
                left: 20.0,
                top: 244.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 249.0,
                child:  GeneratedSigninWidget(),
              ),
              Positioned(
                left: 71.0,
                top: 513.0,
                right: null,
                bottom: null,
                width: 234.0,
                height: 9.0,
                child: GeneratedCreateaccountWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 542.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 140.0,
                child: GeneratedSocialaccountsWidget(),
              )
            ]),
      ),
    ));
  }
}
