import 'package:flutter/material.dart';
import 'package:flutterapp/relishersapp/generated25confirmorderwidget/generated/GeneratedAddmoreWidget2.dart';
import 'package:flutterapp/relishersapp/generated25confirmorderwidget/generated/GeneratedBarsTopbars1Widget10.dart';
import 'package:flutterapp/relishersapp/generated25confirmorderwidget/generated/GeneratedTotalWidget1.dart';
import 'package:flutterapp/relishersapp/generated25confirmorderwidget/generated/GeneratedCTAPrimaryWidget12.dart';
import 'package:flutterapp/relishersapp/generated25confirmorderwidget/generated/GeneratedOrderlistWidget7.dart';

/* Frame 25- Confirm Order
    Autogenerated by FlutLab FTF Generator
  */
class Generated25ConfirmOrderWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 465.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 100.0,
                child: GeneratedTotalWidget1(),
              ),
              Positioned(
                left: 20.0,
                top: 589.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 98.0,
                child: GeneratedAddmoreWidget2(),
              ),
              Positioned(
                left: 20.0,
                top: 734.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 48.0,
                child: GeneratedCTAPrimaryWidget12(),
              ),
              Positioned(
                left: 20.0,
                top: 112.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 337.0,
                child: GeneratedOrderlistWidget7(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 88.0,
                child: GeneratedBarsTopbars1Widget10(),
              )
            ]),
      ),
    ));
  }
}
