import 'package:flutter/material.dart';
import 'package:flutterapp/relishersapp/generated21searchfoodwidget/generated/GeneratedTopbarWidget3.dart';
import 'package:flutterapp/relishersapp/generated21searchfoodwidget/generated/GeneratedTopcategoriesWidget.dart';
import 'package:flutterapp/relishersapp/generated21searchfoodwidget/generated/GeneratedTopbarWidget4.dart';
import 'package:flutterapp/relishersapp/generated21searchfoodwidget/generated/GeneratedTopcategoriesWidget1.dart';
import 'package:flutterapp/relishersapp/generated21searchfoodwidget/generated/GeneratedTabbar2Widget6.dart';
import 'package:flutterapp/relishersapp/generated21searchfoodwidget/generated/GeneratedTabbar2Widget8.dart';

/* Frame 21-Search food
    Autogenerated by FlutLab FTF Generator
  */
class Generated21SearchfoodWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -52.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 98.0,
                child: GeneratedTopbarWidget3(),
              ),
              Positioned(
                left: -1245.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 98.0,
                child: GeneratedTopbarWidget4(),
              ),
              Positioned(
                left: 20.0,
                top: 80.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 720.0,
                child: GeneratedTopcategoriesWidget(),
              ),
              Positioned(
                left: -1225.0,
                top: 132.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 720.0,
                child: GeneratedTopcategoriesWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 720.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 88.0,
                child: GeneratedTabbar2Widget6(),
              ),
              Positioned(
                left: -1245.0,
                top: 724.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 88.0,
                child: GeneratedTabbar2Widget8(),
              )
            ]),
      ),
    ));
  }
}
