import 'package:flutter/material.dart';
import 'package:flutterapp/relishersapp/generated14featuredpartnerswidget/generated/GeneratedTabbar2Widget2.dart';
import 'package:flutterapp/relishersapp/generated14featuredpartnerswidget/generated/GeneratedFeaturedPartnersWidget3.dart';
import 'package:flutterapp/relishersapp/generated14featuredpartnerswidget/generated/GeneratedBarsTopbars1Widget6.dart';

/* Frame 14-Featured Partners
    Autogenerated by FlutLab FTF Generator
  */
class Generated14FeaturedPartnersWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1205.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 375.0,
                      height: 1205.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 88.0,
                              child: GeneratedBarsTopbars1Widget6(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 112.0,
                              right: null,
                              bottom: null,
                              width: 335.0,
                              height: 1084.0,
                              child: GeneratedFeaturedPartnersWidget3(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 1117.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 88.0,
                              child: GeneratedTabbar2Widget2(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
