import 'package:flutter/material.dart';
import 'package:flutterapp/relishersapp/generated18addpaymentmethodwidget/generated/GeneratedTopbarWidget2.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/relishersapp/generated18addpaymentmethodwidget/generated/GeneratedScancardWidget.dart';
import 'package:flutterapp/relishersapp/generated18addpaymentmethodwidget/generated/GeneratedDateCopyWidget.dart';
import 'package:flutterapp/relishersapp/generated18addpaymentmethodwidget/generated/GeneratedTextWidget16.dart';
import 'package:flutterapp/relishersapp/generated18addpaymentmethodwidget/generated/GeneratedDateWidget.dart';
import 'package:flutterapp/relishersapp/generated18addpaymentmethodwidget/generated/GeneratedPrimaryCTAWidget.dart';
import 'package:flutterapp/relishersapp/generated18addpaymentmethodwidget/generated/GeneratedCardnumberWidget.dart';

/* Frame 18-Add payment method
    Autogenerated by FlutLab FTF Generator
  */
class Generated18AddpaymentmethodWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 32.0,
                top: 112.0,
                right: null,
                bottom: null,
                width: 310.0,
                height: 92.0,
                child: GeneratedTextWidget16(),
              ),
              Positioned(
                left: 20.0,
                top: 238.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 54.0,
                child: GeneratedCardnumberWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 308.0,
                right: null,
                bottom: null,
                width: 170.0,
                height: 54.0,
                child: GeneratedDateWidget(),
              ),
              Positioned(
                left: 206.0,
                top: 308.0,
                right: null,
                bottom: null,
                width: 149.0,
                height: 54.0,
                child: GeneratedDateCopyWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.8933333333333333;

                  final double height =
                      constraints.maxHeight * 0.059113300492610835;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.05333333333333334,
                        y: constraints.maxHeight * 0.9039408866995073,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedScancardWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.8933333333333333;

                  final double height =
                      constraints.maxHeight * 0.059113300492610835;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.05333333333333334,
                        y: constraints.maxHeight * 0.8251231527093597,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedPrimaryCTAWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 88.0,
                child: GeneratedTopbarWidget2(),
              )
            ]),
      ),
    ));
  }
}
