import 'package:flutter/material.dart';
import 'package:flutterapp/relishersapp/generated32locationswidget/generated/GeneratedForm4searchdeactiveWidget2.dart';
import 'package:flutterapp/relishersapp/generated32locationswidget/generated/GeneratedBarsTopbars1Widget18.dart';
import 'package:flutterapp/relishersapp/generated32locationswidget/generated/GeneratedRecentaddressWidget.dart';

/* Frame 32-Locations
    Autogenerated by FlutLab FTF Generator
  */
class Generated32LocationsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () =>
          Navigator.pushNamed(context, '/Generated34ReferToFriendWidget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 375.0,
          height: 812.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 375.0,
                  height: 88.0,
                  child: GeneratedBarsTopbars1Widget18(),
                ),
                Positioned(
                  left: 20.0,
                  top: 112.0,
                  right: null,
                  bottom: null,
                  width: 335.0,
                  height: 48.0,
                  child: GeneratedForm4searchdeactiveWidget2(),
                ),
                Positioned(
                  left: 20.0,
                  top: 184.0,
                  right: null,
                  bottom: null,
                  width: 334.0,
                  height: 194.0,
                  child: GeneratedRecentaddressWidget(),
                )
              ]),
        ),
      ),
    ));
  }
}
