import 'package:flutter/material.dart';

/* Component Address
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAddressWidget6 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 339.0,
      height: 66.0,
    ));
  }
}
