import 'package:flutter/material.dart';
import 'package:flutterapp/relishersapp/generated09loginbyphonenumberwidget/generated/GeneratedBarsTopbars1Widget4.dart';
import 'package:flutterapp/relishersapp/generated09loginbyphonenumberwidget/generated/GeneratedTextWidget7.dart';
import 'package:flutterapp/relishersapp/generated09loginbyphonenumberwidget/generated/GeneratedFrameWidget.dart';
import 'package:flutterapp/relishersapp/generated09loginbyphonenumberwidget/generated/GeneratedForm3phoneWidget.dart';
import 'package:flutterapp/relishersapp/generated09loginbyphonenumberwidget/generated/GeneratedKeyboards2Widget.dart';
import 'package:flutterapp/relishersapp/generated09loginbyphonenumberwidget/generated/GeneratedCTAPrimaryWidget7.dart';

/* Frame 09-Login by phone number
    Autogenerated by FlutLab FTF Generator
  */
class Generated09LoginbyphonenumberWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 88.0,
                child: GeneratedBarsTopbars1Widget4(),
              ),
              Positioned(
                left: 38.0,
                top: 112.0,
                right: null,
                bottom: null,
                width: 299.0,
                height: 80.0,
                child: GeneratedTextWidget7(),
              ),
              Positioned(
                left: 20.0,
                top: 226.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 64.0,
                child: GeneratedForm3phoneWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 449.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 48.0,
                child: GeneratedCTAPrimaryWidget7(),
              ),
              Positioned(
                left: 0.0,
                top: 521.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 291.0,
                child: GeneratedKeyboards2Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 255.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 24.0,
                child: GeneratedFrameWidget(),
              )
            ]),
      ),
    ));
  }
}
