import 'package:flutter/material.dart';
import 'package:flutterapp/relishersapp/generated03walkthroughwidget/generated/GeneratedIPhoneXStatusBarsStatusBarWidget2.dart';
import 'package:flutterapp/relishersapp/generated03walkthroughwidget/generated/GeneratedTextWidget2.dart';
import 'package:flutterapp/relishersapp/generated03walkthroughwidget/generated/GeneratedIndicatorWidget2.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/relishersapp/generated03walkthroughwidget/generated/GeneratedG12Widget2.dart';
import 'package:flutterapp/relishersapp/generated03walkthroughwidget/generated/GeneratedCTAPrimaryWidget2.dart';
import 'package:flutterapp/relishersapp/generated03walkthroughwidget/generated/GeneratedIllustrationsWidget2.dart';
import 'package:flutterapp/relishersapp/generated03walkthroughwidget/generated/GeneratedWelcometoRelishersWidget2.dart';

/* Frame 03-Walkthrough
    Autogenerated by FlutLab FTF Generator
  */
class Generated03WalkthroughWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedIPhoneXStatusBarsStatusBarWidget2(),
              ),
              Positioned(
                left: 37.0,
                top: 557.0,
                right: null,
                bottom: null,
                width: 312.0,
                height: 78.0,
                child: GeneratedTextWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.8201045735677084;

                  final double height =
                      constraints.maxHeight * 0.4463552841412023;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.09866666666666667,
                        y: constraints.maxHeight * 0.19088669950738915,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedIllustrationsWidget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 169.0,
                top: 657.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 5.0,
                child: GeneratedIndicatorWidget2(),
              ),
              Positioned(
                left: 20.0,
                top: 684.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 48.0,
                child: GeneratedCTAPrimaryWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.17333333333333334;

                  final double height =
                      constraints.maxHeight * 0.08004926108374384;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.08266666666666667,
                        y: constraints.maxHeight * 0.1687192118226601,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedG12Widget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.6933333333333334;

                  final double height =
                      constraints.maxHeight * 0.06280788177339902;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.2613333333333333,
                        y: constraints.maxHeight * 0.08251231527093596,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedWelcometoRelishersWidget2(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
