import 'package:flutter/material.dart';
import 'package:flutterapp/relishersapp/generated22searchingfoodwidget/generated/GeneratedTopbarWidget5.dart';
import 'package:flutterapp/relishersapp/generated22searchingfoodwidget/generated/GeneratedRecentSearchWidget.dart';
import 'package:flutterapp/relishersapp/generated22searchingfoodwidget/generated/GeneratedKeyboards1Widget2.dart';

/* Frame 22-Searching food
    Autogenerated by FlutLab FTF Generator
  */
class Generated22SearchingfoodWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () =>
          Navigator.pushNamed(context, '/Generated23SearchresultsWidget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 375.0,
          height: 812.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 375.0,
                  height: 98.0,
                  child: GeneratedTopbarWidget5(),
                ),
                Positioned(
                  left: 20.0,
                  top: 132.0,
                  right: null,
                  bottom: null,
                  width: 334.0,
                  height: 360.0,
                  child: GeneratedRecentSearchWidget(),
                ),
                Positioned(
                  left: 0.0,
                  top: 479.0,
                  right: null,
                  bottom: null,
                  width: 375.0,
                  height: 333.0,
                  child: GeneratedKeyboards1Widget2(),
                )
              ]),
        ),
      ),
    ));
  }
}
