import 'package:flutter/material.dart';
import 'package:flutterapp/relishersapp/generatediphonexstatusbarsstatusbarwidget38/generated/GeneratedBgWidget236.dart';
import 'package:flutterapp/relishersapp/generatediphonexstatusbarsstatusbarwidget38/generated/GeneratedIPhoneXStatusBarsStatusBarBlackWidget40.dart';

/* Component iPhone X/Status Bars/Status Bar
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhoneXStatusBarsStatusBarWidget38 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 375.0,
      height: 44.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 44.0,
              child: GeneratedBgWidget236(),
            ),
            Positioned(
              left: null,
              top: null,
              right: null,
              bottom: null,
              width: 375.0,
              height: 44.0,
              child: GeneratedIPhoneXStatusBarsStatusBarBlackWidget40(),
            )
          ]),
    ));
  }
}
