import 'package:flutter/material.dart';
import 'package:flutterapp/relishersapp/generated27accountsettingswidget/generated/GeneratedTabbar2Widget12.dart';
import 'package:flutterapp/relishersapp/generated27accountsettingswidget/generated/GeneratedPersonalinfoWidget.dart';
import 'package:flutterapp/relishersapp/generated27accountsettingswidget/generated/GeneratedNotificationsWidget.dart';
import 'package:flutterapp/relishersapp/generated27accountsettingswidget/generated/GeneratedIPhoneXStatusBarsStatusBarWidget25.dart';
import 'package:flutterapp/relishersapp/generated27accountsettingswidget/generated/GeneratedMoreWidget.dart';
import 'package:flutterapp/relishersapp/generated27accountsettingswidget/generated/GeneratedToptextWidget1.dart';

/* Frame 27-Account settings
    Autogenerated by FlutLab FTF Generator
  */
class Generated27AccountsettingsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1253.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 375.0,
                      height: 1253.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 44.0,
                              child:
                                  GeneratedIPhoneXStatusBarsStatusBarWidget25(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 68.0,
                              right: null,
                              bottom: null,
                              width: 311.0,
                              height: 75.0,
                              child: GeneratedToptextWidget1(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 167.0,
                              right: null,
                              bottom: null,
                              width: 355.0,
                              height: 432.0,
                              child: GeneratedPersonalinfoWidget(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 627.0,
                              right: null,
                              bottom: null,
                              width: 355.0,
                              height: 252.0,
                              child: GeneratedNotificationsWidget(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 907.0,
                              right: null,
                              bottom: null,
                              width: 355.0,
                              height: 238.0,
                              child: GeneratedMoreWidget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 1165.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 88.0,
                              child: GeneratedTabbar2Widget12(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
