import 'package:flutter/material.dart';
import 'package:flutterapp/relishersapp/generated13homepagewidget/generated/GeneratedFeaturedPartnersWidget.dart';
import 'package:flutterapp/relishersapp/generated13homepagewidget/generated/GeneratedAllRestaurantsWidget.dart';
import 'package:flutterapp/relishersapp/generated13homepagewidget/generated/GeneratedBarsTopbars2Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/relishersapp/generated13homepagewidget/generated/GeneratedBannerWidget.dart';
import 'package:flutterapp/relishersapp/generated13homepagewidget/generated/GeneratedTabbar2Widget.dart';
import 'package:flutterapp/relishersapp/generated13homepagewidget/generated/GeneratedHeaderWidget.dart';
import 'package:flutterapp/relishersapp/generated13homepagewidget/generated/GeneratedBestPicksRestaurantsbyteamWidget.dart';

/* Frame 13-Homepage
    Autogenerated by FlutLab FTF Generator
  */
class Generated13HomepageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 2178.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 375.0,
                      height: 2103.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 3.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 114.0,
                              child: GeneratedBarsTopbars2Widget(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 138.0,
                              right: null,
                              bottom: null,
                              width: 335.0,
                              height: 185.0,
                              child: GeneratedHeaderWidget(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 357.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 295.0,
                              child: GeneratedFeaturedPartnersWidget(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 890.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 327.0,
                              child:
                                  GeneratedBestPicksRestaurantsbyteamWidget(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 1251.0,
                              right: null,
                              bottom: null,
                              width: 335.0,
                              height: 927.0,
                              child: GeneratedAllRestaurantsWidget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 2015.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 88.0,
                              child: GeneratedTabbar2Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.8933333333333333;

                                final double height =
                                    constraints.maxHeight * 0.08083689966714218;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.05333333333333334,
                                      y: constraints.maxHeight *
                                          0.3262006657156443,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedBannerWidget(),
                                      ))
                                ]);
                              }),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
