import 'package:flutter/material.dart';
import 'package:flutterapp/relishersapp/generatedicons2424widget/generated/GeneratedIcons24Widget.dart';
import 'package:flutterapp/relishersapp/generatedicons2424widget/generated/GeneratedIcons2424Widget1.dart';

/* Frame Icons(24*24)
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIcons2424Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 464.0,
      height: 528.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.zero,
              child: Container(
                color: Color.fromARGB(255, 255, 255, 255),
              ),
            ),
            Positioned(
              left: 60.0,
              top: 124.0,
              right: null,
              bottom: null,
              width: 344.0,
              height: 344.0,
              child: GeneratedIcons24Widget(),
            ),
            Positioned(
              left: 60.0,
              top: 60.0,
              right: null,
              bottom: null,
              width: 213.0,
              height: 26.0,
              child: GeneratedIcons2424Widget1(),
            )
          ]),
    ));
  }
}
