import 'package:flutter/material.dart';
import 'package:flutterapp/relishersapp/generatedbarstopbars3widget1/generated/GeneratedIPhoneXStatusBarsStatusBarWidget40.dart';
import 'package:flutterapp/relishersapp/generatedbarstopbars3widget1/generated/GeneratedFilterWidget3.dart';
import 'package:flutterapp/relishersapp/generatedbarstopbars3widget1/generated/GeneratedIcon24backWidget76.dart';
import 'package:flutterapp/relishersapp/generatedbarstopbars3widget1/generated/GeneratedSearchResultsWidget.dart';
import 'package:flutterapp/relishersapp/generatedbarstopbars3widget1/generated/GeneratedBgWidget268.dart';

/* Component Bars/Top bars/3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBarsTopbars3Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 375.0,
      height: 88.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 88.0,
              child: GeneratedBgWidget268(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 44.0,
              child: GeneratedIPhoneXStatusBarsStatusBarWidget40(),
            ),
            Positioned(
              left: 20.0,
              top: 54.0,
              right: null,
              bottom: null,
              width: 24.0,
              height: 24.0,
              child: GeneratedIcon24backWidget76(),
            ),
            Positioned(
              left: 131.0,
              top: 60.0,
              right: null,
              bottom: null,
              width: 115.0,
              height: 14.0,
              child: GeneratedSearchResultsWidget(),
            ),
            Positioned(
              left: 318.0,
              top: 60.0,
              right: null,
              bottom: null,
              width: 42.0,
              height: 17.0,
              child: GeneratedFilterWidget3(),
            )
          ]),
    ));
  }
}
