import 'package:flutter/material.dart';
import 'package:flutterapp/relishersapp/generated16addtoorderwidget/generated/GeneratedTopTextWidget.dart';
import 'package:flutterapp/relishersapp/generated16addtoorderwidget/generated/GeneratedAddinstructionsWidget.dart';
import 'package:flutterapp/relishersapp/generated16addtoorderwidget/generated/GeneratedHeaderareaWidget1.dart';
import 'package:flutterapp/relishersapp/generated16addtoorderwidget/generated/GeneratedBottmcookiesWidget.dart';
import 'package:flutterapp/relishersapp/generated16addtoorderwidget/generated/GeneratedCTAPrimaryWidget9.dart';
import 'package:flutterapp/relishersapp/generated16addtoorderwidget/generated/GeneratedTopcookiesWidget.dart';
import 'package:flutterapp/relishersapp/generated16addtoorderwidget/generated/GeneratedCartnumberWidget.dart';

/* Frame 16-Add to order
    Autogenerated by FlutLab FTF Generator
  */
class Generated16AddtoorderWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1668.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 375.0,
                      height: 1668.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 280.0,
                              child: GeneratedHeaderareaWidget1(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 304.0,
                              right: null,
                              bottom: null,
                              width: 328.0,
                              height: 119.0,
                              child: GeneratedTopTextWidget(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 457.0,
                              right: null,
                              bottom: null,
                              width: 335.0,
                              height: 464.0,
                              child: GeneratedTopcookiesWidget(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 955.0,
                              right: null,
                              bottom: null,
                              width: 335.0,
                              height: 464.0,
                              child: GeneratedBottmcookiesWidget(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 1440.0,
                              right: null,
                              bottom: null,
                              width: 335.0,
                              height: 37.0,
                              child: GeneratedAddinstructionsWidget(),
                            ),
                            Positioned(
                              left: 102.0,
                              top: 1511.0,
                              right: null,
                              bottom: null,
                              width: 171.0,
                              height: 54.0,
                              child: GeneratedCartnumberWidget(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 1599.0,
                              right: null,
                              bottom: null,
                              width: 335.0,
                              height: 48.0,
                              child: GeneratedCTAPrimaryWidget9(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
