import 'package:flutter/material.dart';
import 'package:flutterapp/relishersapp/generatedform1activewidget/generated/GeneratedIcon24phoneWidget2.dart';
import 'package:flutterapp/relishersapp/generatedform1activewidget/generated/GeneratedBgWidget240.dart';
import 'package:flutterapp/relishersapp/generatedform1activewidget/generated/GeneratedPhoneorEmailaddressWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Component Form/1/Active
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedForm1ActiveWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 335.0,
      height: 54.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth;

                final double height = constraints.maxHeight;

                return Stack(children: [
                  TransformHelper.translate(
                      x: 0,
                      y: 0,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedBgWidget240(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.6447761194029851;

                final double height =
                    constraints.maxHeight * 0.25925925925925924;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.05970149253731343,
                      y: constraints.maxHeight * 0.3888888888888889,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedPhoneorEmailaddressWidget(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.07164179104477612;

                final double height =
                    constraints.maxHeight * 0.4444444444444444;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.8686567164179104,
                      y: constraints.maxHeight * 0.2777777777777778,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedIcon24phoneWidget2(),
                      ))
                ]);
              }),
            )
          ]),
    ));
  }
}
