import 'package:flutter/material.dart';
import 'package:flutterapp/relishersapp/generated24yourorderswidget/generated/GeneratedPastordersWidget.dart';
import 'package:flutterapp/relishersapp/generated24yourorderswidget/generated/GeneratedBarsTopbars1Widget9.dart';
import 'package:flutterapp/relishersapp/generated24yourorderswidget/generated/GeneratedUpcomingordersWidget1.dart';
import 'package:flutterapp/relishersapp/generated24yourorderswidget/generated/GeneratedTabbar2Widget10.dart';

/* Frame 24-Your orders
    Autogenerated by FlutLab FTF Generator
  */
class Generated24YourordersWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 88.0,
                child: GeneratedBarsTopbars1Widget9(),
              ),
              Positioned(
                left: 20.0,
                top: 112.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 469.0,
                child: GeneratedPastordersWidget(),
              ),
              Positioned(
                left: 23.0,
                top: 605.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 414.0,
                child: GeneratedUpcomingordersWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 724.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 88.0,
                child: GeneratedTabbar2Widget10(),
              )
            ]),
      ),
    ));
  }
}
