import 'package:flutter/material.dart';
import 'package:flutterapp/relishersapp/generated20searchrestaurantswidget/generated/GeneratedSearchWidget8.dart';
import 'package:flutterapp/relishersapp/generated20searchrestaurantswidget/generated/GeneratedTopRestaurantsWidget.dart';
import 'package:flutterapp/relishersapp/generated20searchrestaurantswidget/generated/GeneratedTabbar2Widget4.dart';
import 'package:flutterapp/relishersapp/generated20searchrestaurantswidget/generated/GeneratedIPhoneXStatusBarsStatusBarWidget17.dart';

/* Frame 20-Search Restaurants
    Autogenerated by FlutLab FTF Generator
  */
class Generated20SearchRestaurantsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedIPhoneXStatusBarsStatusBarWidget17(),
              ),
              Positioned(
                left: 20.0,
                top: 68.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 88.0,
                child: GeneratedSearchWidget8(),
              ),
              Positioned(
                left: 20.0,
                top: 190.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 658.0,
                child: GeneratedTopRestaurantsWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 724.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 88.0,
                child: GeneratedTabbar2Widget4(),
              )
            ]),
      ),
    ));
  }
}
