import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/relishersapp/generated02walkthroughwidget/generated/GeneratedTextWidget1.dart';
import 'package:flutterapp/relishersapp/generated02walkthroughwidget/generated/GeneratedCTAPrimaryWidget1.dart';
import 'package:flutterapp/relishersapp/generated02walkthroughwidget/generated/GeneratedIPhoneXStatusBarsStatusBarWidget1.dart';
import 'package:flutterapp/relishersapp/generated02walkthroughwidget/generated/GeneratedG12Widget1.dart';
import 'package:flutterapp/relishersapp/generated02walkthroughwidget/generated/GeneratedIllustrationsWidget1.dart';
import 'package:flutterapp/relishersapp/generated02walkthroughwidget/generated/GeneratedWelcometoRelishersWidget1.dart';
import 'package:flutterapp/relishersapp/generated02walkthroughwidget/generated/GeneratedIndicatorWidget1.dart';

/* Frame 02-Walkthrough
    Autogenerated by FlutLab FTF Generator
  */
class Generated02WalkthroughWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedIPhoneXStatusBarsStatusBarWidget1(),
              ),
              Positioned(
                left: 32.0,
                top: 535.0,
                right: null,
                bottom: null,
                width: 312.0,
                height: 78.0,
                child: GeneratedTextWidget1(),
              ),
              Positioned(
                left: 38.0,
                top: 196.0,
                right: null,
                bottom: null,
                width: 299.0,
                height: 299.0,
                child: GeneratedIllustrationsWidget1(),
              ),
              Positioned(
                left: 167.0,
                top: 653.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 5.0,
                child: GeneratedIndicatorWidget1(),
              ),
              Positioned(
                left: 20.0,
                top: 684.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 48.0,
                child: GeneratedCTAPrimaryWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.17333333333333334;

                  final double height =
                      constraints.maxHeight * 0.08004926108374384;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.08,
                        y: constraints.maxHeight * 0.19088669950738915,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedG12Widget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.6933333333333334;

                  final double height =
                      constraints.maxHeight * 0.06280788177339902;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.25866666666666666,
                        y: constraints.maxHeight * 0.10467980295566502,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedWelcometoRelishersWidget1(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
